# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/schollz/progressbar
%global goipath         github.com/schollz/progressbar/v3
%global forgeurl        https://github.com/schollz/progressbar
Version:                3.8.3

%gometa

%global common_description %{expand:
A really basic thread-safe progress bar for Golang applications.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A really basic thread-safe progress bar for Golang applications

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/k0kubun/go-ansi)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/mitchellh/colorstring)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Oct 09 2021 Adam Thiede <adamj@mailbox.org> - 3.8.3-1%{?dist}
- Initial package

