# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/mmcdole/gofeed
%global goipath         github.com/mmcdole/gofeed
Version:                1.1.3

%gometa

%global common_description %{expand:
Parse RSS, Atom and JSON feeds in Go.}

%global golicenses      LICENSE
%global godocs          docs README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Parse RSS, Atom and JSON feeds in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/json-iterator/go)
BuildRequires:  golang(github.com/mmcdole/goxpp)
BuildRequires:  golang(github.com/PuerkitoBio/goquery)
BuildRequires:  golang(github.com/urfave/cli)
BuildRequires:  golang(golang.org/x/net/html)
BuildRequires:  golang(golang.org/x/net/html/charset)
BuildRequires:  golang(golang.org/x/text/transform)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Oct 04 2021 Adam Thiede <adamj@mailbox.org> - 1.1.3-1%{?dist}
- Initial package

