# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/makeworld-the-better-one/amfora
%global goipath         github.com/makeworld-the-better-one/amfora
Version:                1.8.0

%gometa

%global common_description %{expand:
A fancy terminal browser for the Gemini protocol.}

%global golicenses      LICENSE display/license.go display/license.sh
%global godocs          CHANGELOG.md NOTES.md README.md THANKS.md\\\
                        contrib/gemini-wiki/README.md contrib/gemini-\\\
                        wiki/requirements.txt contrib/themes/README.md\\\
                        rr/README.md webbrowser/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A fancy terminal browser for the Gemini protocol

License:        GPL-3.0-only
# FIXME: Upstream uses unknown SPDX tag GPL-3.0-only!
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/dustin/go-humanize)
BuildRequires:  golang(github.com/gdamore/tcell/v2)
BuildRequires:  golang(github.com/makeworld-the-better-one/go-gemini)
BuildRequires:  golang(github.com/makeworld-the-better-one/go-isemoji)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/mmcdole/gofeed)
BuildRequires:  golang(github.com/rkoesters/xdg/basedir)
BuildRequires:  golang(github.com/rkoesters/xdg/userdirs)
BuildRequires:  golang(github.com/schollz/progressbar/v3)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(gitlab.com/tslocum/cview)
BuildRequires:  golang(golang.org/x/text/encoding/ianaindex)
BuildRequires:  golang(golang.org/x/text/unicode/norm)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/amfora %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE display/license.go display/license.sh
%doc CHANGELOG.md NOTES.md README.md THANKS.md contrib/gemini-wiki/README.md
%doc contrib/gemini-wiki/requirements.txt contrib/themes/README.md rr/README.md
%doc webbrowser/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Oct 04 2021 Adam Thiede <adamj@mailbox.org> - 1.8.0-1%{?dist}
- Initial package

