# Generated by go2rpm 1.5.0
%bcond_without check

# https://gitlab.com/tslocum/cview
%global goipath         gitlab.com/tslocum/cview
%global forgeurl        https://gitlab.com/tslocum/cview
Version:                1.5.3

%gometa

%global common_description %{expand:
Terminal-based user interface toolkit}

%global golicenses      LICENSE
%global godocs          CHANGELOG CONTRIBUTING.md DESIGN.md FORK.md README.md\\\
                        demos/box/README.md demos/button/README.md\\\
                        demos/checkbox/README.md demos/dropdown/README.md\\\
                        demos/flex/README.md demos/form/README.md\\\
                        demos/frame/README.md demos/grid/README.md\\\
                        demos/inputfield/README.md demos/list/README.md\\\
                        demos/modal/README.md demos/panels/README.md\\\
                        demos/primitive/README.md demos/table/README.md\\\
                        demos/textview/README.md demos/treeview/README.md\\\
                        demos/unicode/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        !!! cview has moved to [code.rocketnine.space](https://code.rocketnine.space/tslocum/cview) !!

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gdamore/tcell/v2)
BuildRequires:  golang(github.com/lucasb-eyer/go-colorful)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/rivo/uniseg)
BuildRequires:  golang(gitlab.com/tslocum/cbind)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in demos/textview demos/inputfield/simple demos/inputfield/autocomplete demos/treeview demos/modal demos/unicode demos/presentation demos/button demos/dropdown demos/inputfield/autocompleteasync demos/list demos/progressbar demos/primitive demos/form demos/tabbedpanels demos/table demos/focusmanager demos/box demos/frame demos/checkbox demos/grid demos/flex demos/panels; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG CONTRIBUTING.md DESIGN.md FORK.md README.md demos/box/README.md
%doc demos/button/README.md demos/checkbox/README.md demos/dropdown/README.md
%doc demos/flex/README.md demos/form/README.md demos/frame/README.md
%doc demos/grid/README.md demos/inputfield/README.md demos/list/README.md
%doc demos/modal/README.md demos/panels/README.md demos/primitive/README.md
%doc demos/table/README.md demos/textview/README.md demos/treeview/README.md
%doc demos/unicode/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Oct 04 2021 Adam Thiede <adamj@mailbox.org> - 1.5.3-1%{?dist}
- Initial package

