# Generated by go2rpm 1.5.0
%bcond_without check

# https://code.rocketnine.space/tslocum/cview
%global goipath         code.rocketnine.space/tslocum/cview
%global forgeurl        https://code.rocketnine.space/tslocum/cview
Version:                1.5.7

%gometa

%global common_description %{expand:
Terminal-based user interface toolkit}

%global golicenses      LICENSE
%global godocs          CHANGELOG CONTRIBUTING.md DESIGN.md FORK.md README.md\\\
                        demos/box/README.md demos/button/README.md\\\
                        demos/checkbox/README.md demos/dropdown/README.md\\\
                        demos/flex/README.md demos/form/README.md\\\
                        demos/frame/README.md demos/grid/README.md\\\
                        demos/inputfield/README.md demos/list/README.md\\\
                        demos/modal/README.md demos/panels/README.md\\\
                        demos/primitive/README.md demos/table/README.md\\\
                        demos/textview/README.md demos/treeview/README.md\\\
                        demos/unicode/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        MIT

#URL:            %{gourl}
URL:            %{goipath}
#Source0:        %{gosource}
Source0:        https://code.rocketnine.space/tslocum/cview/archive/v%{version}.tar.gz

BuildRequires:  golang(code.rocketnine.space/tslocum/cbind)
BuildRequires:  golang(github.com/gdamore/tcell/v2)
BuildRequires:  golang(github.com/lucasb-eyer/go-colorful)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/rivo/uniseg)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in demos/box demos/presentation demos/frame demos/progressbar demos/button demos/focusmanager demos/table demos/treeview demos/unicode demos/tabbedpanels demos/textview demos/panels demos/inputfield/autocompleteasync demos/primitive demos/modal demos/grid demos/form demos/inputfield/simple demos/list demos/flex demos/inputfield/autocomplete demos/checkbox demos/dropdown; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG CONTRIBUTING.md DESIGN.md FORK.md README.md demos/box/README.md
%doc demos/button/README.md demos/checkbox/README.md demos/dropdown/README.md
%doc demos/flex/README.md demos/form/README.md demos/frame/README.md
%doc demos/grid/README.md demos/inputfield/README.md demos/list/README.md
%doc demos/modal/README.md demos/panels/README.md demos/primitive/README.md
%doc demos/table/README.md demos/textview/README.md demos/treeview/README.md
%doc demos/unicode/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Oct 04 2021 Adam Thiede <adamj@mailbox.org> - 1.5.7-1%{?dist}
- Initial package

