# Generated by go2rpm 1.5.0
%bcond_without check

# https://gitlab.com/tslocum/cbind
%global goipath         gitlab.com/tslocum/cbind
%global forgeurl        https://gitlab.com/tslocum/cbind
Version:                v0.1.5

%gometa

%global common_description %{expand:
Key event handling library for tcell }

%global golicenses      LICENSE
%global godocs          CHANGELOG README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gdamore/tcell/v2)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in whichkeybind; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Oct 04 2021 Adam Thiede <adamj@mailbox.org> - 0.1.5-1%{?dist}
- Initial package

