# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/makeworld-the-better-one/go-isemoji
%global goipath         github.com/makeworld-the-better-one/go-isemoji
Version:                1.2.0

%gometa

%global common_description %{expand:
Go library to test if a string is an emoji.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go library to test if a string is an emoji

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Oct 04 2021 Adam Thiede <adamj@mailbox.org> - 1.2.0-1%{?dist}
- Initial package

